blog/urls.py
from django.contrib import admin
from django.urls import path

from blog import views as blog_views

app_name = 'blog'


urlpatterns = [
    path('post/', blog_views.blog, name = 'home'),
    path('post/<int:post_id>/', blog_views.post, name = 'post'),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from home import views as home_views

app_name = 'home' #add o app_name para deixaer mais seguro e dinamico 

urlpatterns = [
    path('', home_views.home, name = 'home' ), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views as blog_views
from home import views as home_views


urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),    
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from blog.data import posts 


# Create your views here.
def blog(request): 
    context =  {
        'text': 'ESTAMOS NO BLOG ACTUALIZANDO', 
        'posts': posts
    }
    return render(request, 'blog\home.html', context)

from django.http import Http404, HttpResponse

def post(request, post_id): 

    #isso servira para quando eu acessar o post que desejo n seja preciso 
    found_post = None
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None: 
        raise Http404('POST N ENCONTRADO, N EXISTE PROVAVELMENTE')        
    

    context =  {
        'text': 'ESTOU EM UM DOS POSTS', 
        'post': found_post,
        'title': found_post['title'] + ' - ', #para aparecer o titulo do post no topo(como titulo do site)
    }
    return render(request, 'blog\post.html', context)

home/views.py
from django.shortcuts import render


# Create your views here.
def home(request): 
    
    context =  {
        'text': 'ESTAMOS NA HOME ACTUALIZANDO', 
        'title': 'TITULO DO CONTEXT - '
        }

    return render( request, 'home\index.html', context)

blog/templates/blog/home.html
{% extends 'global\base.html' %}

{% block TEXTO %} {{ text }} {% endblock TEXTO %}

{% block posts %} 
    {%for post in posts %}
    {% include 'global\partials\postblock.html' %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends 'global\base.html' %}

{% block TEXTO %} {{ text }} {% endblock TEXTO %}

{% block posts %} 
    <article class="post"> 
        <header> 
            <h1 class="post single-post">
                <a href="{% url 'blog:post' post.id %}">
                    {{ post.title }}
                </a>
            </h1>
        </header>
        <div class="post__body">
        {{ post.body }}
    </article>
{% endblock posts %}

home/templates/home/index.html
{% extends 'global\base.html' %}

{% block TEXTO %} 
{{ text}}
{% endblock TEXTO %}